{
    'name': 'Catálogo de insumos',
    'summary': 'Esquema v2: División > Grupo (etiqueta) > Familia > Clasificador, clave GG-MMMM-FFF-CCC-NN, genéricos, especialidades, equipos, marcas con código, fotos, asistente guiado, etiqueta QR',
    'version': '19.0.1.0.0',
    'category': 'Distribución de insumos',
    'author': 'Alphaqueb Consulting SAS',
    'license': 'LGPL-3',
    'icon': '/biotex_catalog/static/description/icon.svg',
    'depends': ['biotex_base', 'product', 'stock', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'security/catalog_security.xml',
        'data/schema_data.xml',
        'views/biotex_schema_views.xml',
        'views/biotex_brand_views.xml',
        'views/biotex_equipment_views.xml',
        'views/product_category_views.xml',
        'views/product_template_views.xml',
        'views/classifier_action.xml',
        'wizard/reorder_wizard_views.xml',
        'report/product_label_report.xml',
        'views/menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'biotex_catalog/static/src/**/*',
        ],
    },
    'installable': True,
}
